// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// YoutubePlaylistClient is the client API for YoutubePlaylist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YoutubePlaylistClient interface {
	List(ctx context.Context, in *PlaylistRequest, opts ...grpc.CallOption) (*PlaylistResponse, error)
}

type youtubePlaylistClient struct {
	cc grpc.ClientConnInterface
}

func NewYoutubePlaylistClient(cc grpc.ClientConnInterface) YoutubePlaylistClient {
	return &youtubePlaylistClient{cc}
}

func (c *youtubePlaylistClient) List(ctx context.Context, in *PlaylistRequest, opts ...grpc.CallOption) (*PlaylistResponse, error) {
	out := new(PlaylistResponse)
	err := c.cc.Invoke(ctx, "/api.YoutubePlaylist/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YoutubePlaylistServer is the server API for YoutubePlaylist service.
// All implementations must embed UnimplementedYoutubePlaylistServer
// for forward compatibility
type YoutubePlaylistServer interface {
	List(context.Context, *PlaylistRequest) (*PlaylistResponse, error)
	mustEmbedUnimplementedYoutubePlaylistServer()
}

// UnimplementedYoutubePlaylistServer must be embedded to have forward compatible implementations.
type UnimplementedYoutubePlaylistServer struct {
}

func (UnimplementedYoutubePlaylistServer) List(context.Context, *PlaylistRequest) (*PlaylistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedYoutubePlaylistServer) mustEmbedUnimplementedYoutubePlaylistServer() {}

// UnsafeYoutubePlaylistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YoutubePlaylistServer will
// result in compilation errors.
type UnsafeYoutubePlaylistServer interface {
	mustEmbedUnimplementedYoutubePlaylistServer()
}

func RegisterYoutubePlaylistServer(s grpc.ServiceRegistrar, srv YoutubePlaylistServer) {
	s.RegisterService(&YoutubePlaylist_ServiceDesc, srv)
}

func _YoutubePlaylist_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YoutubePlaylistServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.YoutubePlaylist/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YoutubePlaylistServer).List(ctx, req.(*PlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YoutubePlaylist_ServiceDesc is the grpc.ServiceDesc for YoutubePlaylist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YoutubePlaylist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.YoutubePlaylist",
	HandlerType: (*YoutubePlaylistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _YoutubePlaylist_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PATH/youtube.proto",
}
